
language: nix

# cache:
#   directories:
#     - $HOME/nix.store

before_install:
    - sudo mkdir -p /etc/nix
    # - echo "substituters = file://$HOME/nix.store https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf > /dev/null
    # - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf > /dev/null

script:
    - nix-build --arg buildExamples true

# before_cache:
#     - mkdir -p $HOME/nix.store
#     - nix copy --to file://$HOME/nix.store $(nix-instantiate)
#     - nix copy --to file://$HOME/nix.store ./result
